spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1

            - id: arena-service-characters
              uri: lb://ARENA-SERVICE
              predicates:
                - Path=/api/characters/**
              filters:
                - StripPrefix=1

            - id: arena-service-matches
              uri: lb://ARENA-SERVICE
              predicates:
                - Path=/api/matches/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway