spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: monster-service-monsters
              uri: lb://MONSTER-SERVICE
              predicates:
                - Path=/api/monsters/**
              filters:
                - StripPrefix=1

            - id: monster-service-categories
              uri: lb://MONSTER-SERVICE
              predicates:
                - Path=/api/categories/**
              filters:
                - StripPrefix=1

            - id: region-service-regions
              uri: lb://REGION-SERVICE
              predicates:
                - Path=/api/regions/**
              filters:
                - StripPrefix=1

            - id: region-service-sightings
              uri: lb://REGION-SERVICE
              predicates:
                - Path=/api/sightings/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway