INSERT INTO category (id, name, description) VALUES
                                                 (1, 'Sea Monster', 'Criaturas extraordinárias que habitam os oceanos. Muitas foram domesticadas pela Igreja do Senhor das Tempestades'),
                                                 (2, 'Spirit World Creature', 'Entidades originárias do Mundo dos Espíritos, podendo estar vivas ou mortas. Distintas dos mortos-vivos'),
                                                 (3, 'Mutant', 'Raça dominante na Segunda Época. Humanos ou animais transformados pelos efeitos negativos de características Beyonder'),
                                                 (4, 'Ancient Race', 'Raças que dominaram o mundo em épocas passadas, como Elfos, Fênixes e Nagas. A maioria entrou em extinção após o Cataclismo'),
                                                 (5, 'Beyonder Creature', 'Criaturas comuns que sobreviveram à ingestão de uma característica Beyonder e adquiriram poderes sobrenaturais'),
                                                 (6, 'Forsaken Land Creature', 'Criaturas únicas encontradas na Terra Abandonada dos Deuses, região isolada do mundo principal');

INSERT INTO monsters (id, name, category_id, region_id, threat_level, status, description, abilities, sighting_count) VALUES
                                                                                                                          (1, 'Murloc', 1, 1, 3, 'COMMON', 'O monstro marinho mais comum da Sonia Sea. Corpo coberto de escamas verde-escuras com gosma verde. Mais de 190cm de altura, olhos saltados e guelras nas bochechas. Suas escamas são tão duras que revólveres causam dano mínimo. Sua bexiga é ingrediente da poção Marinheiro (Sequência 9)', 'Resistência física, natação veloz, ataque corpo a corpo com garras', 0),
                                                                                                                          (2, 'Labo Octopus', 1, 1, 6, 'RARE', 'Polvo misterioso cujo sangue é azul como o céu e borbulha como se conectado ao Mundo dos Espíritos. Ingrediente chave da poção Vidente (Sequência 9) e Arquivista (Sequência 7)', 'Sangue espiritual, geração de bolhas ilusórias, conexão com o Mundo dos Espíritos', 0),
                                                                                                                          (3, 'Shapeshifter', 6, 3, 7, 'RARE', 'Também chamado de Transformista na Cidade de Prata. Não possui inteligência para comunicação, mas é extremamente hábil em armar emboscadas e se disfarçar de outras pessoas para completar uma caçada', 'Disfarce perfeito, armadilhas, camuflagem', 0),
                                                                                                                          (4, 'Asmano', 6, 3, 8, 'RARE', 'Monstro de lenda antiga. Assemelha-se a um cérebro humano gigante, grande o suficiente para preencher uma sala inteira. Capaz de criar alucinações aterrorizantes. Seu cérebro é ingrediente da poção Arquivista (Sequência 6). Deve ser isolado como ouro para neutralizar sua influência mental', 'Criação de alucinações, ataque mental, influência psíquica passiva', 0),
                                                                                                                          (5, 'Naga', 4, 1, 6, 'RARE', 'Criatura com corpo superior humano e inferior de serpente, com seis braços e extrema agilidade. Segundo o Mito da Criação, a essência do Criador Original se tornou as Nagas. Durante a Era das Trevas, submeteram-se ao Rei Elfo Soniathryme e governaram os fundos do mar. Há uma tribo ativa a 1200 milhas náuticas de Sonia Island', 'Seis braços, agilidade sobrenatural, combate aquático, submissão ao Rei Elfo', 0),
                                                                                                                          (6, 'Mutant', 3, 4, 5, 'COMMON', 'Raça dominante da Segunda Época sob o Rei Mutante Kvastir. Humanos transformados pelos efeitos negativos de certas características Beyonder. Seus desejos explodem ao contato com determinadas cenas ou objetos, transformando-os em monstros sedentos por sangue e massacre', 'Transformação em monstro ao ser estimulado, força e brutalidade, desejo de sangue', 0),
                                                                                                                          (7, 'Harpy', 2, 6, 5, 'RARE', 'Monstro capaz de dar pesadelos e acordar pessoas de seus sonhos. Sua origem é uma jovem do Reino Haagenti que, ao ser morta pelo irmão por transgressão matrimonial, absorveu a essência do Mundo dos Espíritos. Usada no ritual de avanço do Sonhador (Sequência 5)', 'Indução de pesadelos, despertar forçado de sonhos, manipulação onírica', 0),
                                                                                                                          (8, 'Eye Creature', 2, 6, 7, 'RARE', 'Aparência de sombra transparente e turva com um único olho azul-fantasmagórico. Ao redor do olho principal existem olhos menores similares. Ao obter a alma verdadeira de um Saqueador do Mundo dos Espíritos, pode se transformar em um Feiticeiro Bizarro completo. Seu olho principal e sangue são ingredientes da poção Sequência 4', 'Visão sobrenatural, múltiplos olhos, absorção de alma espiritual', 0),
                                                                                                                          (9, 'Phoenix', 4, 4, 7, 'EXTINCT', 'Raça dominante da Segunda Época sob o Ancestral Fênix Gregrace. Segundo o Mito da Criação, o cabelo do Criador Original se tornou Fênixes. Uma das raças que dominou a Segunda Época, agora extinta', 'Renascimento das chamas, voo, manipulação de fogo', 0),
                                                                                                                          (10, 'Stone Giant', 4, 2, 6, 'RARE', 'Gigantes de pedra localizados nas ilhas do Mar de Ruínas. Alguns não são monstros reais e portanto não possuem valor. São um dos filhos do mar conectados ao Ritual de Oração do Mar em Porto Santa', 'Força colossal, corpo de pedra, conexão com rituais do mar', 0);