input {
  tcp {
    port => 5000
    codec => json_lines
  }
}
filter {
  mutate {
    add_field => {
      "ambiente" => "desenvolvimento"
      "stack" => "monster-catalog-system"
    }
  }
}
output {
  stdout {
    codec => rubydebug
  }
}